// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "swift26",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "swift26",
            targets: ["AppModule"],
            bundleIdentifier: "com.journeyHome.swift26",
            teamIdentifier: "LQXURPH4NG",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bowl),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("forest_bg.png")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)